### ISSUE TITLE
How to use PutFile Processor in Apache nifi running in Docker Container?

### ISSUE THREAD

**Issue by vsharathchandra** [xmlking/nifi-examples#3]
I have used a simple flow given here https://github.com/xmlking/nifi-examples/tree/master/http-get-route .I am getting a "java.nio.file.AccessDeniedException" error in PutFile Processor.I guess it is because I am running nifi inside Docker.What Directory path should I pass to PutFIle ?

**Comment by xmlking** [comment]
you can mount a volume within docker and use it for application specify storage needs.
